FROM node:14.17.3

# env set
ARG DB_USERNAME
ENV DB_USERNAME=$DB_USERNAME
ARG DB_PASSWORD
ENV DB_PASSWORD=$DB_PASSWORD
ARG DB_DATABASE
ENV DB_DATABASE=$DB_DATABASE
ARG DB_HOST
ENV DB_HOST=$DB_HOST
ARG TOKEN_SECRET_KEY
ENV TOKEN_SECRET_KEY=$TOKEN_SECRET_KEY
ARG ACCESS_KEY_ID
ENV ACCESS_KEY_ID=$ACCESS_KEY_ID
ARG SECRET_ACCESS_KEY
ENV SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY
ARG S3_REGION
ENV S3_REGION=$S3_REGION

# folder set
RUN mkdir -p /app
WORKDIR /app
ADD . /app/
RUN echo "FOLDER CREATED"

RUN node -v
RUN echo "NODE VERSION CHECK"

# install
RUN rm yarn.lock || true
RUN yarn
RUN echo "INSTALL CREATED"

# build
RUN yarn build
RUN echo "BUILD CREATED"

# 가상 머신에 오픈할 포트
ENV HOST 0.0.0.0
EXPOSE 3000

CMD [ "yarn", "start" ]